apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "url-shortener.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "url-shortener.name" . }}

    spec:
      containers:
        - name: api

          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-secret
                  key: DATABASE_URL

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-config
                  key: REDIS_HOST

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "url-shortener.fullname" . }}-secret
                  key: JWT_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}
spec:
  selector:
    app: {{ include "url-shortener.name" . }}

  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}

  type: {{ .Values.api.service.type }}