apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-config

data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDatabase | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}